apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {CLUSTER_NAME}
resources:
  - namespace.yaml
  -  ../../apps/base/vsphere/release.yaml
configMapGenerator:
  - name: provisioner-values
    files:
      - values.yaml=provisioner-values.yaml
configurations:
  -  ../../apps/base/vsphere/kustomizeconfig.yaml